apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
      nodePort: 32432
