apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-project-auth
  labels:
    app: crud-project-auth
spec:
  selector:
    matchLabels:
      app: crud-project-auth
  template:
    metadata:
      labels:
        app: crud-project-auth
    spec:
      containers:
        - name: crud-project-auth
          image: nexus-service.tools.svc.cluster.local:8083/v2/repository/docker-private/crud-project-auth/manifests/latest
          imagePullpolicy: always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-project-auth-service
spec:
  selector:
    app: crud-project-auth
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
