apiVersion: v1
kind: Service
metadata:
  name: crud-project-auth-service
  namespace: deploy
  labels:
    app: crud-project-auth
spec:
  selector:
    app: crud-project-auth
  ports:
    - port: 3000         # Porta que será exposta
      targetPort: 3000   # Porta usada no contêiner
  type: NodePort         # Ou ClusterIP / LoadBalancer dependendo da necessidade
